---
channel: edge
addons:
  grott:
    repository: egguy/addon-grott
    target: grott
    image: ghcr.io/egguy/addon-grott/{arch}
  grott-beta:
    repository: egguy/addon-grott-beta
    target: grott-beta
    image: ghcr.io/egguy/grott-beta/{arch}
